app/urls.py
from django.conf.urls import include, patterns, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.conf import settings
from django.views.generic.base import TemplateView
# from filebrowser.sites import site
from students.urls import students, labs

admin.autodiscover()

urlpatterns = i18n_patterns('',
    url(r'^page_settings/', include('page_extend.urls')),
    url(r'^students-url/marks/', include('students.urls.labs')),
    url(r'^students-url/', include('students.urls.students')),
    url(r'^marks-url/', include('students.urls.marks')),
    url(r'^textpage-app/', include('textpage.urls')),
    url(r'^articles/', include('articles.urls')),
    url(r'^main-page/', include('main_page.urls')),
    url(r'^tracking/', include('tracking_ex.urls')),
    url(r'^browser', include('browser.urls', namespace='browser', app_name='browser')),
    url(r'^file_browser', include('my_file_browser.urls')),
    url(r'^robots\.txt$', TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/$', "app.views.login_user"),
    url(r'^logout/$', "django.contrib.auth.views.logout"),

    # url(r'^admin/filebrowser/', include(site.urls)),
    # url(r'^grappelli/', include('grappelli.urls')),
    # url(r'^admin/', include(admin.site.urls)),

    url(r'^', include('cms.urls')),
)

# if settings.DEBUG:
urlpatterns = patterns('',
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    url(r'', include('django.contrib.staticfiles.urls')),
) + urlpatterns

browser/urls.py
from django.conf.urls import patterns, url

__author__ = 'm'


urlpatterns = patterns('browser.views',
    url(r'/(?P<path>.*)$', 'index', name='index'),
)

browser/models.py
from django.db import models

# Create your models here.

browser/views.py
import os
from django.contrib.auth.decorators import login_required
from django.core.context_processors import media
from django.core.files.storage import default_storage
from django.shortcuts import render

# Create your views here.

@login_required
def index(request, path):

    dirs, files = default_storage.listdir(path)

    dirs = [{
        'path': os.path.join(path, d),
        'name': d,
    } for d in dirs]

    files = [{
        'name': f,
        'url': default_storage.url(os.path.join(path, f)),
        'path': default_storage.path(os.path.join(path, f)),
    } for f in files]

    return render(request, "browser/index.html", {
        'dirs': dirs,
        'files': files,
        'previous': os.path.dirname(path)
    })

app/templates/browser/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
    {#    {% include "elements/scripts.html" %}#}
    {#    {% include "elements/styles.html" %}#}
    <script src="{% static "bower_components/jquery/dist/jquery.min.js" %}"></script>
    <link rel="stylesheet" href="{% static "lib/bootstrap/bootstrap.min.css" %}"/>
</head>
<body>

<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
    <div class="list-group">
        <a class="list-group-item" href="{% url 'browser:index' previous %}">
            ..
        </a>
        {% for dir in dirs %}
            <a class="list-group-item" href="{% url 'browser:index' dir.path %}">
                {{ dir.name }}
            </a>
        {% endfor %}
    </div>
</div>
<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
    {% for file in files %}
        <a class="list-group-item file" href="{{ file.url }}">
            {{ file.name }}
        </a>
    {% endfor %}
</div>
<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
    <iframe id="preview" src="" frameborder="0" style="width: 100%;height: 100%;">

    </iframe>
</div>

<script>
    $('.file').click(function () {
        $("#preview").attr('src', this.href);
        return false;
    })
</script>

</body>
</html>